import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

const isDev = process.argv[2] === "dev";

const ctx = await esbuild.context({
  entryPoints: ["main.ts"],
  bundle: true,
  banner: { js: banner },
  sourcemap: isDev ? "inline" : false,
  platform: "browser",
  target: "es2023",
  format: "cjs",
  outfile: "main.js",
  external: ["obsidian"],
  logLevel: "info",
});

if (isDev) {
  await ctx.watch();
  console.log("Watching...");
} else {
  await ctx.rebuild();
  await ctx.dispose();
  console.log("Built.");
}
